version: '3'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend

  # Backend Service
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    container_name: backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mealbooking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: postgres:16
    container_name: mealbooking_postgres
    restart: always
    environment:
      POSTGRES_DB: mealbooking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  
volumes:
  postgres_data:
  