// Generated by Selenium IDE
package tqs.hw1.selenium;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;

import org.junit.jupiter.api.BeforeAll;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.hamcrest.MatcherAssert.assertThat;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MarkAsUsedTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void markAsUsed() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1920, 1053));
    driver.findElement(By.cssSelector(".meal-card-horizontal:nth-child(3) .reserve-btn")).click();
    driver.findElement(By.cssSelector(".view-toggle")).click();
    driver.findElement(By.cssSelector(".reservation-item:nth-child(1) > .reservation-meal")).click();
    driver.findElement(By.cssSelector(".verify-btn")).click();
    assertThat(driver.switchTo().alert().getText(), is("Reserva marcada como utilizada!"));
  }
}
